### PR TITLE
Api request setup

### PR DESCRIPTION
**Pull request by Nesmith-Charlesii**
All model requests call to backend with the exception of flags and comments. Will refine but these should suffice for api consumption.

### CODE REVIEW

**Comment by Nesmith-Charlesii** [comment]
> Just noticed a couple things but otherwise looks good:
> 
> 1. We should add the `withCredentials: true` option to all Axios calls to ensure that the session cookie is being added to requests.
> 2. React Query handles errors and makes them available if they're thrown through their request hooks so we don't really need to include try-catch blocks in our base API call functions.
> 3. In `get()`, it seems like the only query param that's actually getting set is the `limit` param. We're obviously going to need to be able to set a whole host of parameters so it would make a lot more sense to simply accept a `params` object and just pass this to the Axios call.
> 4. Not all of our requests are going to have the same `Content-Type` header. The `POST /experiences` endpoint expects a `multipart/form-data` MIME type (for the experience pictures along with the other experience data). I think it makes more sense for the base functions to accept an optional `headers` object param so that headers can be set directly if need be but otherwise let Axios decide the proper content-type.
> 5. In `getById()`, the `pathParam` parameter is always going to be an object ID so it seems a little clearer to call this param `objectId` or something, right?
> 6. In `delete()`, again, would make more sense just to call the param `objectId` or `documentId` instead of `pathParam` (IMO). And since Axios throws an error for non-successful status codes we could just return the deleted document object upon success and assume that the status was 200 since it didn't throw.

Great advice! Ok, I'll make these changes today. Thank you for clarifying @dwight9339 !

**Comment by Nesmith-Charlesii** [comment]
@dwight9339 The delete endpoint on the backend doesn't return anything except the status code, so we wouldn't be able to return the deleted document object, as after deletion their technically is no document (let me know if I misunderstood). What do you think about keeping this delete function (with the params changed to objectId) in case a user would like to "undo" their deletion? This undo could be temporary until they leave the page or after a certain time period. Either way, we have a response that has the 'doc_deletion' data if we decide to use it.

**Comment by dwight9339** [comment]
It looked like the original method fetched the document before calling the delete endpoint and returned it in an object along with status code. That’s what ‘doc_deletion’ is, right? If so, then we can just return the document that was queried instead of an object with a single member. And since we’ve grabbed the document and stored it client side, that data is still available even after the record has been deleted from the DB on the back end.

**Comment by dwight9339** [comment]
Not super important though. It still works the way it is. Just a stylistic critique. Let me know if I’m being annoying and I’ll only mention the critical stuff

**Review by dwight9339 — APPROVED** [review]

**Comment by Nesmith-Charlesii** [comment]
> It looked like the original method fetched the document before calling the delete endpoint and returned it in an object along with status code. That’s what ‘doc_deletion’ is, right? If so, then we can just return the document that was queried instead of an object with a single member. And since we’ve grabbed the document and stored it client side, that data is still available even after the record has been deleted from the DB on the back end.

Haha nah man be as critical as you feel necessary. I appreciate it. It helps me grow and furthers my understanding. I'm not following what you mean when you say "with a single member", but if I'm understanding correctly, you're saying that once the user has logged in and their data is fetched, we will already have that data available to us on the client side, which means that after we delete the document from the db, we will still have the document object that was fetched at the beginning of the user's session, right? Also, I forgot to change the Headers. I'll get that done in the morning.

**Comment by dwight9339** [comment]
‘’M
    delete = async(objectId: string) => { 
        let response = await axios.get(`${getApiBase()}/${this.model}/${objectId}`, {
            headers: HEADERS,
            withCredentials: true
        });

        let deletedDocument = await axios.delete(`${getApiBase()}/${this.model}/${objectId}`, {
            headers: HEADERS,
            withCredentials: true
        });

        return {
            data: { 
                doc_deletion: response.data, 
                status: deletedDocument.status,
            }
        }
    }
}
‘’’

In my original comment I had said that it was unnecessary to return the status since the function will either return, meaning it received a 200 status or throw an error which will include a status code and, since that’s the case, instead of returning an object with just the document that was deleted (‘doc_deletion’) we can instead return the deleted document without wrapping it in an object. If, in the future, we (or future maintainers) decide we need to return more data, we can easily change the function to do so. Again, not a critical issue, just a stylistic one. If you’re returning an object with only one thing inside it, might as well just return that thing.

 And, not quite. The document we’ll be returning in ‘delete()’ isn’t fetched at the start of the user’s session, it’s fetched when the ‘getById’ endpoint is called at the beginning of the method. Even if that document is deleted from the DB when we call the ‘delete’ endpoint right after, the document that we fetched isn’t deleted, I make sense?

**Comment by Nesmith-Charlesii** [comment]
Ah, understood. I believe we're on the same page, as I already understand that fetching the document in the delete method prior to deleting it from the db will still allow us to store that data on the frontend, which is why I returned it as 'doc_deletion'. From your original comment, I thought you meant otherwise. I do agree that returning the data as is, instead of within an object, makes more sense. Either way, no big deal.

**Comment by Nesmith-Charlesii** [comment]
@dwight9339 I made a few more changes. Give it one more once-over and I'll get this merged.

**Comment by dwight9339** [comment]
Looks good 👍

**Pull request merged**
