### PR TITLE
Display map popup

### PR DESCRIPTION
**Pull request by Nesmith-Charlesii**
Map marker and popup complete. Reaction bar added. All reactions can be clicked and posted only once when they are clicked. Multiple reactions cannot be selected. Image and description added to marker pin.

### CODE REVIEW

**Review by dwight9339 — APPROVED** [review]
Looks good. The reaction buttons look solid but I was under the impression that reactions weren't mutually exclusive and choosing one shouldn't un-choose another. Like, you could say "thanks for sharing" and "will try" or all three even (doesn't really make sense to say you'll try something you've already "me too"-ed but I don't see why there should be hard rules against it necessarily). Nothing breaking, but we can mark it for discussion at our next meeting.

**Comment by Nesmith-Charlesii** [comment]
Makes sense and is an easy fix. I mentioned this during the meeting twice. I'll change it later today.

**Comment by dwight9339** [comment]
Ah, my bad. I thought I remembered you saying something about not allowing users to post the same reaction twice but I guess I misunderstood. 

I'm thinking it might be a good idea to create some special endpoints for reactions that automatically add the user ID from the user's session data and prevent the same user from posting the same reaction to the same experience more than once. What do you think?

Oh! And speaking of user IDs, I just went back and looked at the `ReactionBar` component to see what that mutation looked like and noticed that you had hard coded a user ID there.

**Comment by dwight9339** [comment]
I created a [PR](https://github.com/communitynostalgiaproject/Nostalgia-Project-Server/pull/43) that updates how the reaction endpoints work and adds a new one allowing reactions to be deleted without needing the ID if you wanna take a look.

**Comment by Nesmith-Charlesii** [comment]
All good man. I'm getting around to this now. I checked out the new endpoint and see that you updated the reaction endpoint. Is this new endpoint necessary if I can already reference the experience ID when fetching reactions by experience ID?

**Comment by dwight9339** [comment]
The logic for adding and removing reactions works great! We still need to update the icons for existing reactions when the component first loads so that the current state of the user's reactions to a post on the server are reflected in the UI though.
Also, currently, handleReactions is updating the UI whether the state of reactions on the backend was updated successfully or not. What we could do instead is maintain the object of selected reactions in the React Query cache and use mutations to update the cache results _optimistically_, meaning we update the UI as if the request was successful and roll back later if the request fails. Here's an example:
```
    const queryClient = useQueryClient();
    // Using ["reactions", experience._id.toString()] as our cache key allows us to cache reaction
    // query results for each experience a user visits
    const { data: selectedReactions } = useQuery(["reactions", experience._id.toString()], async() => {
        const results =  await reactionsRequest.getByUserId({ experienceId: experience["_id"], userId: user["_id"] });
        const userReactions = results.map((reactionDoc: any) => reactionDoc.reaction);

        return {
          meToo: userReactions.includes("meToo"),
          thanksForSharing: userReactions.includes("thanksForSharing"),
          willTry: userReactions.includes("willTry"),
        }
    });

    const postReaction = useMutation(async (data: reactionReqBody) => {
        await reactionsRequest.put(data);
    }, {
      onMutate: async (newData: any) => {
        // Cancel any outgoing refetches (so they don't overwrite our optimistic update)
        await queryClient.cancelQueries(["reactions", experience._id.toString()]);

        // Snapshot the previous value
        const previousData = queryClient.getQueryData(["reactions", experience._id.toString()]);

        // Optimistically update the cache with the new value
        queryClient.setQueryData(["reactions", experience._id.toString()], (oldData: any) => ({
          ...oldData,
          // Assume oldData is an object and we're updating a part of it
          [newData.reaction]: true
        }));

        // Store in mutation's context to reference in case update needs to be rolled back
        return { previousData };
      },
      onError: (err, newData, context) => {
        // Rollback to the previous value
        console.log(`Error posting reaction: ${JSON.stringify(err)}`);
        queryClient.setQueryData(["reactions", experience._id.toString()], context?.previousData);
      },
      onSuccess: () => {
        // Invalidate the cache to force useQuery to refetch the updated
        // value of selectedReactions
        queryClient.invalidateQueries(["reactions", experience._id.toString()]);
      }
    });

    // Same principle but removes the reaction
    const removeReaction = useMutation(async (data: reactionReqBody) => {
      await reactionsRequest.removeReaction(data);
    }, {
      onMutate: async (newData: any) => {
        await queryClient.cancelQueries(["reactions", experience._id.toString()]);

        const previousData = queryClient.getQueryData(["reactions", experience._id.toString()]);

        queryClient.setQueryData(["reactions", experience._id.toString()], (oldData: any) => ({
          ...oldData,
          [newData.reaction]: false
        }));

        return { previousData };
      },
      onError: (err, newData, context) => {
        queryClient.setQueryData(["reactions", experience._id.toString()], context?.previousData);
      },
      onSuccess: () => {
        queryClient.invalidateQueries(["reactions", experience._id.toString()]);
      }
    });

    const handleReaction = async(event: React.MouseEvent<HTMLDivElement>) => {
        if (!selectedReactions) return;
        let reaction = event.currentTarget?.id;
        let experienceId = event.currentTarget?.getAttribute("data-experience");

        if(selectedReactions[reaction as keyof typeof selectedReactions] === false) {
          postReaction.mutate({
            experienceId: experienceId as string,
            reaction: reaction,
          });
        } else {
          removeReaction.mutate({
              experienceId: experienceId as string,
              reaction: reaction,
          })
        }
        // No need to do this manually anymore since the query and mutations handle fetching and updating
        // the state of selectedReaction in the React Query cache
        // setSelectedReaction(reactionState => ({
        //     ...reactionState,
        //     [reaction as keyof typeof reactionState]: !reactionState[reaction as keyof typeof reactionState]
        // }))
    };
```

**Comment by Nesmith-Charlesii** [comment]
I know, and I am already working on that now. I will let you know when it's up and ready.

**Comment by Nesmith-Charlesii** [comment]
I just pushed everything up. This should be good to go. I kept the state changes so as not to close the popup marker after clicking a reaction. If this looks ok to you, I'll go ahead and make the merge.

**Comment by dwight9339** [comment]
We need to use different query keys for each experience `useQuery("reactions", ... ===> useQuery(["reactions", experience._id.toString()], ...`. That way we're caching the query results for each experience visited. Otherwise the reactions for the first experience you visit gets stored in the cache and visiting a new experience just returns the cached reactions from the first experience visited. Other than that it looks good though.

**Comment by Nesmith-Charlesii** [comment]
It fetches the most recent reactions when you click on a new experience. So it should display the reactions for the experience clicked. I'll check it out again tomorrow.

**Comment by dwight9339** [comment]
Check if the branch you're working has this in `src/index.tsx`:
```

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 15 * 60 * 1000, // Global staleTime of 15 minutes
    }
  }
});
```
If not, the cache is getting reset instantly every time and hitting the backend for those reactions every time you visit an experience pin. We don't want that. We want to cache the reactions whenever we visit a pin so that if we click on it again later we already have the cached values handy.

**Comment by Nesmith-Charlesii** [comment]
I don't have that code snippet in src/index.tsx

**Pull request merged**
